keys:
  - &fortytwo age13j46a9vnpc8lga7jr9w0px2aapwpse0wyvne0ea6g4qjm68c2pnsweq49g
creation_rules:
  # We can set up specific regexes with some keys...
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *fortytwo
  # And encrypt everything else with this key.
  - path_regex: .
    key_groups:
    - age:
      - *fortytwo
  # But really, we only really use one key right now, so we don't care that much...
  # And we could add multiple keys everywhere if we'd be encrypting for different recipients.
